In [109]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [110]:
data = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])

In [111]:
data

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [112]:
from sklearn.preprocessing import LabelEncoder

In [113]:
le = LabelEncoder()

In [114]:
data['label'] = le.fit_transform(data['label'])

In [115]:
data

sep_l  sep_w  pet_l  pet_w  label
0      5.1    3.5    1.4    0.2      0
1      4.9    3.0    1.4    0.2      0
2      4.7    3.2    1.3    0.2      0
3      4.6    3.1    1.5    0.2      0
4      5.0    3.6    1.4    0.2      0
..     ...    ...    ...    ...    ...
145    6.7    3.0    5.2    2.3      2
146    6.3    2.5    5.0    1.9      2
147    6.5    3.0    5.2    2.0      2
148    6.2    3.4    5.4    2.3      2
149    5.9    3.0    5.1    1.8      2

[150 rows x 5 columns]

In [116]:
x = data.iloc[:,0:4].values

In [117]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [118]:
y = data.iloc[:,4].values

In [119]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [120]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [121]:
x_train.shape

(120, 4)

In [122]:
x_test.shape

(30, 4)

In [123]:
from keras.models import Sequential
from keras.layers import Dense

In [124]:
model = Sequential([
    Dense(8,input_dim=4,activation='relu'),
    Dense(8,activation='relu'),
    Dense(8,activation='relu'),
    Dense(3,activation='softmax')
])

In [125]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [126]:
model.compile(loss= 'sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [135]:
model.fit(x_train,y_train,epochs=80)

Epoch 1/80
4/4 [==============================] - 0s 0s/step - loss: 0.3100 - accuracy: 0.9417
Epoch 2/80
4/4 [==============================] - 0s 0s/step - loss: 0.3038 - accuracy: 0.9500
Epoch 3/80
4/4 [==============================] - 0s 0s/step - loss: 0.2975 - accuracy: 0.9583
Epoch 4/80
4/4 [==============================] - 0s 0s/step - loss: 0.2922 - accuracy: 0.9583
Epoch 5/80
4/4 [==============================] - 0s 0s/step - loss: 0.2864 - accuracy: 0.9583
Epoch 6/80
4/4 [==============================] - 0s 0s/step - loss: 0.2807 - accuracy: 0.9583
Epoch 7/80
4/4 [==============================] - 0s 0s/step - loss: 0.2751 - accuracy: 0.9583
Epoch 8/80
4/4 [==============================] - 0s 0s/step - loss: 0.2700 - accuracy: 0.9583
Epoch 9/80
4/4 [==============================] - 0s 0s/step - loss: 0.2651 - accuracy: 0.9583
Epoch 10/80
4/4 [==============================] - 0s 0s/step - loss: 0.2596 - accuracy: 0.9583
Epoch 11/80
4/4 [==============================] 

In [136]:
pred = model.predict(x_test)

In [137]:
pred.round(2)

array([[0.  , 0.01, 0.99],
       [0.01, 0.96, 0.03],
       [0.99, 0.01, 0.  ],
       [0.  , 0.01, 0.99],
       [0.99, 0.01, 0.  ],
       [0.  , 0.  , 1.  ],
       [0.99, 0.01, 0.  ],
       [0.  , 0.95, 0.04],
       [0.  , 0.9 , 0.1 ],
       [0.01, 0.98, 0.01],
       [0.  , 0.03, 0.97],
       [0.  , 0.97, 0.02],
       [0.  , 0.88, 0.12],
       [0.  , 0.89, 0.11],
       [0.  , 0.83, 0.17],
       [0.99, 0.01, 0.  ],
       [0.  , 0.87, 0.13],
       [0.  , 0.8 , 0.19],
       [0.98, 0.02, 0.  ],
       [0.99, 0.01, 0.  ],
       [0.  , 0.06, 0.94],
       [0.  , 0.81, 0.19],
       [0.98, 0.02, 0.  ],
       [0.98, 0.02, 0.  ],
       [0.  , 0.4 , 0.6 ],
       [0.99, 0.01, 0.  ],
       [0.98, 0.02, 0.  ],
       [0.01, 0.97, 0.02],
       [0.04, 0.95, 0.01],
       [0.98, 0.02, 0.  ]], dtype=float32)

In [138]:
pred.shape

(30, 3)

In [139]:
np.argmax(pred,axis=1)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [140]:
from sklearn.metrics import confusion_matrix,classification_report

In [141]:
confusion_matrix(y_test,np.argmax(pred,axis=1))

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]], dtype=int64)

In [142]:
print(classification_report(y_test,np.argmax(pred,axis=1)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

