In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])

In [3]:
data

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
encoder = OneHotEncoder(sparse=False)

In [13]:
y = data['label']

In [14]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: label, Length: 150, dtype: object

In [15]:
y =  np.array(y).reshape(-1,1)

In [16]:
y = encoder.fit_transform(y)

In [17]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [18]:
x = data.iloc[:,0:4].values

In [19]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
x_train.shape

(120, 4)

In [23]:
x_test.shape

(30, 4)

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model = Sequential([
    Dense(8,input_dim=4,activation='relu'),
    Dense(8,activation='relu'),
    Dense(8,activation='relu'),
    Dense(3,activation='softmax')
])

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [30]:
model.fit(x_train,y_train,epochs=50)

Epoch 1/50
4/4 [==============================] - 0s 0s/step - loss: 1.3550 - accuracy: 0.3667
Epoch 2/50
4/4 [==============================] - 0s 0s/step - loss: 1.2420 - accuracy: 0.3667
Epoch 3/50
4/4 [==============================] - 0s 5ms/step - loss: 1.1560 - accuracy: 0.3667
Epoch 4/50
4/4 [==============================] - 0s 0s/step - loss: 1.0998 - accuracy: 0.3667
Epoch 5/50
4/4 [==============================] - 0s 5ms/step - loss: 1.0475 - accuracy: 0.3667
Epoch 6/50
4/4 [==============================] - 0s 0s/step - loss: 1.0097 - accuracy: 0.3667
Epoch 7/50
4/4 [==============================] - 0s 5ms/step - loss: 0.9779 - accuracy: 0.3667
Epoch 8/50
4/4 [==============================] - 0s 0s/step - loss: 0.9539 - accuracy: 0.4667
Epoch 9/50
4/4 [==============================] - 0s 0s/step - loss: 0.9286 - accuracy: 0.6917
Epoch 10/50
4/4 [==============================] - 0s 0s/step - loss: 0.9064 - accuracy: 0.6917
Epoch 11/50
4/4 [=============================

In [31]:
pred =model.predict(x_test)

In [33]:
pred.round(2)

array([[0.02, 0.37, 0.61],
       [0.15, 0.37, 0.47],
       [0.89, 0.06, 0.05],
       [0.01, 0.34, 0.65],
       [0.85, 0.09, 0.07],
       [0.01, 0.35, 0.64],
       [0.85, 0.08, 0.07],
       [0.07, 0.38, 0.56],
       [0.07, 0.38, 0.55],
       [0.12, 0.38, 0.5 ],
       [0.02, 0.36, 0.63],
       [0.07, 0.38, 0.55],
       [0.06, 0.38, 0.56],
       [0.06, 0.38, 0.56],
       [0.05, 0.38, 0.57],
       [0.84, 0.09, 0.07],
       [0.05, 0.38, 0.57],
       [0.06, 0.39, 0.56],
       [0.82, 0.1 , 0.08],
       [0.87, 0.07, 0.06],
       [0.02, 0.37, 0.61],
       [0.04, 0.38, 0.58],
       [0.75, 0.13, 0.11],
       [0.8 , 0.11, 0.09],
       [0.03, 0.37, 0.6 ],
       [0.84, 0.09, 0.07],
       [0.75, 0.14, 0.12],
       [0.09, 0.38, 0.52],
       [0.17, 0.38, 0.45],
       [0.79, 0.11, 0.09]], dtype=float32)

In [ ]:
np.argmax(pred)